name: CementCalc
description: A new Flutter project.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  path_provider: ^2.1.2

flutter:
  assets:
    - assets/settings.svg
    - assets/undo.svg
